M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-19T10:10:53+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T10:10:53+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X144.77Y-79.49
X144.77Y-85.27
M30
